name: dmiso
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - plyfile=0.8.1
  - trimesh==4.0.5
  - SciPy==1.7.3
  - tqdm
  - pip:
    - chumpy==0.70
    - smplx==0.1.28
    - imageio==2.27.0
    - lpips==0.1.4
    - imageio-ffmpeg==0.4.9
    - opencv-python==4.9.0.80
